config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'admin/index'
  get 'admins/index'
  get 'home/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :coasters
  resources :events
  resources :innovation_grants
  resources :news_pieces
  resources :partners
  resources :admin
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/coasters', to: 'pages#coasters'
  get '/home', to: 'pages#home'
  get '/donate', to: 'pages#donate'
  get '/news', to: 'pages#news_pieces'
  get '/events', to: 'pages#events'
  get '/products', to: 'pages#products'
  get '/volunteer', to: 'pages#volunteer'
  get '/make_event', to: 'pages#make_event'
  get '/innovation', to: 'pages#innovation'
  get '/innovation_details', to: 'pages#innovation_details'
  get '/innovation_application', to: 'pages#innovation_application'
  get '/admin', to: 'pages#admin'
  get '/gallery', to: 'pages#gallery'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coaster.rb
class Coaster < ApplicationRecord
end

app/controllers/coasters_controller.rb
class CoastersController < ApplicationController
  before_action :set_coaster, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /coasters or /coasters.json
  def index
    @coasters = Coaster.all
  end

  # GET /coasters/1 or /coasters/1.json
  def show
  end

  # GET /coasters/new
  def new
    @coaster = Coaster.new
  end

  # GET /coasters/1/edit
  def edit
  end

  # POST /coasters or /coasters.json
  def create
    @coaster = Coaster.new(coaster_params)

    respond_to do |format|
      if @coaster.save
        format.html { redirect_to coaster_url(@coaster), notice: "Coaster was successfully created." }
        format.json { render :show, status: :created, location: @coaster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coasters/1 or /coasters/1.json
  def update
    respond_to do |format|
      if @coaster.update(coaster_params)
        format.html { redirect_to coaster_url(@coaster), notice: "Coaster was successfully updated." }
        format.json { render :show, status: :ok, location: @coaster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coasters/1 or /coasters/1.json
  def destroy
    @coaster.destroy

    respond_to do |format|
      format.html { redirect_to coasters_url, notice: "Coaster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coaster
      @coaster = Coaster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coaster_params
      params.require(:coaster).permit(:quanity, :address, :latitude, :longitude, :date)
    end
end

app/helpers/coasters_helper.rb
module CoastersHelper
end

app/views/coasters/_form.html.erb
<%= form_with(model: coaster) do |form| %>
  <% if coaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coaster.errors.count, "error") %> prohibited this coaster from being saved:</h2>

      <ul>
        <% coaster.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quanity %>
    <%= form.number_field :quanity %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coasters/edit.html.erb
<h1>Editing Coaster</h1>

<%= render 'form', coaster: @coaster %>

<%= link_to 'Show', @coaster %> |
<%= link_to 'Back', coasters_path %>

app/views/coasters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coasters</h1>

<table>
  <thead>
    <tr>
      <th>Quanity</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coasters.each do |coaster| %>
      <tr>
        <td><%= coaster.quanity %></td>
        <td><%= coaster.address %></td>
        <td><%= coaster.latitude %></td>
        <td><%= coaster.longitude %></td>
        <td><%= coaster.date %></td>
        <td><%= link_to 'Show', coaster %></td>
        <td><%= link_to 'Edit', edit_coaster_path(coaster) %></td>
        <td><%= link_to 'Destroy', coaster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coaster', new_coaster_path %>

app/views/coasters/new.html.erb
<h1>New Coaster</h1>

<%= render 'form', coaster: @coaster %>

<%= link_to 'Back', coasters_path %>

app/views/coasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quanity:</strong>
  <%= @coaster.quanity %>
</p>

<p>
  <strong>Address:</strong>
  <%= @coaster.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @coaster.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @coaster.longitude %>
</p>

<p>
  <strong>Date:</strong>
  <%= @coaster.date %>
</p>

<%= link_to 'Edit', edit_coaster_path(@coaster) %> |
<%= link_to 'Back', coasters_path %>