config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'admin/index'
  get 'admins/index'
  get 'home/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :coasters
  resources :events
  resources :innovation_grants
  resources :news_pieces
  resources :partners
  resources :admin
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/coasters', to: 'pages#coasters'
  get '/home', to: 'pages#home'
  get '/donate', to: 'pages#donate'
  get '/news', to: 'pages#news_pieces'
  get '/events', to: 'pages#events'
  get '/products', to: 'pages#products'
  get '/volunteer', to: 'pages#volunteer'
  get '/make_event', to: 'pages#make_event'
  get '/innovation', to: 'pages#innovation'
  get '/innovation_details', to: 'pages#innovation_details'
  get '/innovation_application', to: 'pages#innovation_application'
  get '/admin', to: 'pages#admin'
  get '/gallery', to: 'pages#gallery'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/innovation_grant.rb
class InnovationGrant < ApplicationRecord
end

app/controllers/innovation_grants_controller.rb
class InnovationGrantsController < ApplicationController
  before_action :set_innovation_grant, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /innovation_grants or /innovation_grants.json
  def index
    @innovation_grants = InnovationGrant.all
  end

  # GET /innovation_grants/1 or /innovation_grants/1.json
  def show
  end

  # GET /innovation_grants/new
  def new
    @innovation_grant = InnovationGrant.new
  end

  # GET /innovation_grants/1/edit
  def edit
  end

  # POST /innovation_grants or /innovation_grants.json
  def create
    @innovation_grant = InnovationGrant.new(innovation_grant_params)

    respond_to do |format|
      if @innovation_grant.save
        format.html { redirect_to innovation_grant_url(@innovation_grant), notice: "Innovation grant was successfully created." }
        format.json { render :show, status: :created, location: @innovation_grant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @innovation_grant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /innovation_grants/1 or /innovation_grants/1.json
  def update
    respond_to do |format|
      if @innovation_grant.update(innovation_grant_params)
        format.html { redirect_to innovation_grant_url(@innovation_grant), notice: "Innovation grant was successfully updated." }
        format.json { render :show, status: :ok, location: @innovation_grant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @innovation_grant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /innovation_grants/1 or /innovation_grants/1.json
  def destroy
    @innovation_grant.destroy

    respond_to do |format|
      format.html { redirect_to innovation_grants_url, notice: "Innovation grant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_innovation_grant
      @innovation_grant = InnovationGrant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def innovation_grant_params
      params.require(:innovation_grant).permit(:project_name, :organisation_name, :project_description, :year_awarded, :link_url)
    end
end

app/helpers/innovation_grants_helper.rb
module InnovationGrantsHelper
end

app/views/innovation_grants/_form.html.erb
<%= form_with(model: innovation_grant) do |form| %>
  <% if innovation_grant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(innovation_grant.errors.count, "error") %> prohibited this innovation_grant from being saved:</h2>

      <ul>
        <% innovation_grant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name %>
  </div>

  <div class="field">
    <%= form.label :organisation_name %>
    <%= form.text_field :organisation_name %>
  </div>

  <div class="field">
    <%= form.label :project_description %>
    <%= form.text_area :project_description %>
  </div>

  <div class="field">
    <%= form.label :year_awarded %>
    <%= form.number_field :year_awarded %>
  </div>

  <div class="field">
    <%= form.label :link_url %>
    <%= form.text_field :link_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/innovation_grants/edit.html.erb
<h1>Editing Innovation Grant</h1>

<%= render 'form', innovation_grant: @innovation_grant %>

<%= link_to 'Show', @innovation_grant %> |
<%= link_to 'Back', innovation_grants_path %>

app/views/innovation_grants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Innovation Grants</h1>

<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>Organisation name</th>
      <th>Project description</th>
      <th>Year awarded</th>
      <th>Link url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @innovation_grants.each do |innovation_grant| %>
      <tr>
        <td><%= innovation_grant.project_name %></td>
        <td><%= innovation_grant.organisation_name %></td>
        <td><%= innovation_grant.project_description %></td>
        <td><%= innovation_grant.year_awarded %></td>
        <td><%= innovation_grant.link_url %></td>
        <td><%= link_to 'Show', innovation_grant %></td>
        <td><%= link_to 'Edit', edit_innovation_grant_path(innovation_grant) %></td>
        <td><%= link_to 'Destroy', innovation_grant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Innovation Grant', new_innovation_grant_path %>

app/views/innovation_grants/new.html.erb
<h1>New Innovation Grant</h1>

<%= render 'form', innovation_grant: @innovation_grant %>

<%= link_to 'Back', innovation_grants_path %>

app/views/innovation_grants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @innovation_grant.project_name %>
</p>

<p>
  <strong>Organisation name:</strong>
  <%= @innovation_grant.organisation_name %>
</p>

<p>
  <strong>Project description:</strong>
  <%= @innovation_grant.project_description %>
</p>

<p>
  <strong>Year awarded:</strong>
  <%= @innovation_grant.year_awarded %>
</p>

<p>
  <strong>Link url:</strong>
  <%= @innovation_grant.link_url %>
</p>

<%= link_to 'Edit', edit_innovation_grant_path(@innovation_grant) %> |
<%= link_to 'Back', innovation_grants_path %>