config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'admin/index'
  get 'admins/index'
  get 'home/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :coasters
  resources :events
  resources :innovation_grants
  resources :news_pieces
  resources :partners
  resources :admin
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/coasters', to: 'pages#coasters'
  get '/home', to: 'pages#home'
  get '/donate', to: 'pages#donate'
  get '/news', to: 'pages#news_pieces'
  get '/events', to: 'pages#events'
  get '/products', to: 'pages#products'
  get '/volunteer', to: 'pages#volunteer'
  get '/make_event', to: 'pages#make_event'
  get '/innovation', to: 'pages#innovation'
  get '/innovation_details', to: 'pages#innovation_details'
  get '/innovation_application', to: 'pages#innovation_application'
  get '/admin', to: 'pages#admin'
  get '/gallery', to: 'pages#gallery'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coaster.rb
class Coaster < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/innovation_grant.rb
class InnovationGrant < ApplicationRecord
end

app/models/news_piece.rb
class NewsPiece < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/coasters_controller.rb
class CoastersController < ApplicationController
  before_action :set_coaster, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /coasters or /coasters.json
  def index
    @coasters = Coaster.all
  end

  # GET /coasters/1 or /coasters/1.json
  def show
  end

  # GET /coasters/new
  def new
    @coaster = Coaster.new
  end

  # GET /coasters/1/edit
  def edit
  end

  # POST /coasters or /coasters.json
  def create
    @coaster = Coaster.new(coaster_params)

    respond_to do |format|
      if @coaster.save
        format.html { redirect_to coaster_url(@coaster), notice: "Coaster was successfully created." }
        format.json { render :show, status: :created, location: @coaster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coasters/1 or /coasters/1.json
  def update
    respond_to do |format|
      if @coaster.update(coaster_params)
        format.html { redirect_to coaster_url(@coaster), notice: "Coaster was successfully updated." }
        format.json { render :show, status: :ok, location: @coaster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coasters/1 or /coasters/1.json
  def destroy
    @coaster.destroy

    respond_to do |format|
      format.html { redirect_to coasters_url, notice: "Coaster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coaster
      @coaster = Coaster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coaster_params
      params.require(:coaster).permit(:quanity, :address, :latitude, :longitude, :date)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :organizer, :date, :description, :image_url, :address, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def donate
  end

  def coasters
  end

  def news_pieces
  end

  def events
  end

  def products
  end

  def admin
  end

  def volunteer
  end

  def make_event
  end

  def innovation
  end

  def innovation_details
  end

  def innovation_application
  end

  def gallery
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /partners or /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1 or /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners or /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to partner_url(@partner), notice: "Partner was successfully created." }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1 or /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to partner_url(@partner), notice: "Partner was successfully updated." }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1 or /partners/1.json
  def destroy
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to partners_url, notice: "Partner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def partner_params
      params.require(:partner).permit(:organisation_name, :organisation_description, :link_url, :image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coasters_helper.rb
module CoastersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/innovation_grants_helper.rb
module InnovationGrantsHelper
end

app/helpers/news_pieces_helper.rb
module NewsPiecesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="d-flex flex-column">
    <footer class="w-100 py-4 flex-shrink-0">
        <div class="container py-4">
            <div class="row gy-4 gx-5">
                <div class="col-lg-4 col-md-6">
                    <h5 class="h1 text-white">FB.</h5>
                    <p class="small text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    <p class="small text-muted mb-0">&copy; Copyrights. All rights reserved. <a class="text-primary" href="#">Bootstrapious.com</a></p>
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Quick links</h5>
                    <ul class="list-unstyled text-muted">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Get started</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Quick links</h5>
                    <ul class="list-unstyled text-muted">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Get started</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6">
                    <h5 class="text-white mb-3">Newsletter</h5>
                    <p class="small text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    <form action="#">
                        <div class="input-group mb-3">
                            <input class="form-control" type="text" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">
                            <button class="btn btn-primary" id="button-addon2" type="button"><i class="fas fa-paper-plane"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="shown-head">
    <div class="logo-head">
      <%= image_tag "logo.png", alt: "…", width: "450", height: "102"%>
    </div>
    <button type="button" class="dropbtn">
      <i class="fa-solid fa-bars" ></i>
    </button>
  </div>
  <div id="myDropdown" class="dropdown-content">
    <ul class="level-1">
      <li><%= link_to "events", events_path %></li>
      <li><%= link_to "about", about_path %></li>
      <li><%= link_to "make_event", make_event_path %></li>
      <li><%= link_to "news_pieces", news_pieces_path %></li>
      <li class="with-submenu">
        <div class="dropbtn-level2a">
          <p>Our Products</p>
          <i class="fa-solid fa-chevron-down"></i>
        </div>
        <div class="level-2a-box">
          <ul id="productList" class="level-2a">
            <li><%= link_to "coasters", coasters_path %></li>
          </ul>
        </div>
      </li>
      <li><%= link_to "volunteer", volunteer_path %></li>
      <li><%= link_to "gallery", gallery_path %></li>
      <li class="with-submenu">
        <div class="dropbtn-level2b" >
          <p>Innovation</p>
          <i class="fa-solid fa-chevron-down"></i>
        </div>
        <div class="level-2b-box">
          <ul id="innovationList" class="level-2b">
            <li><%= link_to "innovation_application", innovation_application_path %></li>
            <li><%= link_to "innovation_details", innovation_details_path %></li>
          </ul>
        <div>
      </li>
      <li><%= link_to "donate", donate_path %></li>
    </ul>
  </div>
</div>

<script>


$(".dropbtn").on("click", function () {
  $(".dropdown-content").toggleClass("show");
});

$(".dropbtn-level2a").on("click", function () {
  $(".level-2a").toggleClass("show");
});

$(".dropbtn-level2b").on("click", function () {
  $(".level-2b").toggleClass("show2");
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8f3356e6fc.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>CGMT</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>

    <%= render "layouts/footer" %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>Cameron and Us</h1>
<p>Our son Cameron took his own life in November 2014 aged just 21. He suffered from depression for seven years before he died, but managed to hide this from us and everyone who knew him. He seemed very happy at university and was planning to do a master’s degree. Outwardly he was always smiling and was always the one who was there to cheer everyone else up. </p>
<hr>
<p>We’ve learnt a lot about suicide since Cameron died, and the statistics are frightening. About ¾ of suicides are male and it is the biggest cause of death in the UK for boys and men under 50. 1 in 10 young people, or about 3 in every school classroom, are experiencing mental health problems at any given time and many people suffer in silence, as our son did. In 2013, there were 1769 road fatalities in the UK (roughly 5 a day), but more shockingly 6233 suicides (17 a day). There are many thousands more suffering from depression, self-harm and eating disorders.</p>
<hr>
<p>To mark Cameron’s life we established the Cameron Grant Memorial Trust in his name. The Trust is registered with the Charity Commission (see this link for details CAMERON GRANT MEMORIAL TRUST) and has Registered Number 1167221. Our Charitable objects are:</p>
<hr>
<p>The preservation and protection of good mental health in particular in young people by:</p>
<ul>
  <li>Raising awareness of young suicide</li>
  <li>Urging all who are suffering in silence to speak up and ask for help</li>
  <li>Supporting all who are fighting to overcome poor mental health, especially young people, and especially where this can be done through outdoor activities like hill-walking and Duke of Edinburgh’s Award</li>
  <li>Assisting in the provision of education and support that will help to increase awareness and knowledge of the issues around mental health and well-being for all and especially amongst young people</li>
</ul>
<p>Poor Mental Health can affect anyone and there is no shame in having an illness, physical or mental and seeking help for it. We hope that by spreading this message openly and honestly and providing support to young people through the Trust we can help many others in Cameron’s memory. We miss Cameron an unbelievable amount and we so wish that he had asked for help.</p>
<hr>
<p>We hope that we can make a difference in the numbers of young people suffering with mental health issues and improve outcomes for all sufferers.</p>
<hr>
<p>If you would like to help us, please contact us – we look forward to hearing from you.</p>
<hr>
<p>To see more pictures of Cameron doing the things he loved, please see About Cameron.</p>
<hr>
<p><strong>Carol & Evan Grant</strong></p>

app/views/pages/donate.html.erb
<p>find me at pages/donate</p>

app/views/pages/gallery.html.erb
<p>find me at pages/gallery</p>

app/views/pages/home.html.erb
<div class="banner">
  <%=image_tag "Tutto Ricco - Fresh Air.png", alt: "…"%>
  <div class="banner-text">
    <h6><strong>9 out of 10</strong> people say that the stigma of mental health problems have had a negative effect on their lives.
    <br>
    We think that’s <strong>too much.</strong>
    <br>
    Help us on <strong>our misson</strong> to <strong>destigmatise mental health.</strong>
    </h6>
    <button type="button" class="btn btn-success">Success</button>
  </div>
</div>

<div class="hope">
  <h6>If your struggling with you’re mental health, then please visit our the Hub of Hope, to find a local mental health service, that can help you.</h6>
  <a href="https://hubofhope.co.uk/"><%=image_tag "HOH.png", alt: "…", class: "hub-logo"%></a>
</div>

<div class="link-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-12 link-card">
        <p class="link-text">Cams' Coasters</p>
        <%= image_tag "Coasters.png", alt: "…", width: "307.2", height: "204.75"%>
      </div>
      <div class="col-lg-4 col-sm-12 link-card">
        <p class="link-text">Innovation Grants</p>
        <%= image_tag "Innovation.png", alt: "…", width: "307.2", height: "204.75"%>
      </div>
      <div class="col-lg-4 col-sm-12 link-card">
        <p class="link-text">Our Other Work</p>
        <%= image_tag "mcdonalds.png", alt: "…", width: "307.2", height: "204.75"%>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-sm-12 link-card">
        <p class="link-text">Events</p>
        <%= image_tag "NIGHTWALK.png", alt: "…", width: "307.2", height: "204.75"%>
      </div>
      <div class="col-lg-4 col-sm-12 link-card">
        <p class="link-text">Fundraising</p>
        <%= image_tag "fundraise.png", alt: "…", width: "307.2", height: "204.75"%>
      </div>
      <div class="col-lg-4 col-sm-12 link-card">
        <%= image_tag "DofE.png", alt: "…", width: "307.2", height: "204.75"%>
        <p class="link-text">Cameron and Us</p>
      </div>
      <div class="row">
      </div>
    </div>
  </div>
</div>
<div class="mindfullness">
  <%=image_tag "Kirsty's Wellbeing Postcard - front.jpg", alt: "…"%>
</div>

app/views/pages/innovation.html.erb
<p>find me at pages/innovation</p>

app/views/pages/innovation_application.html.erb
<p>find me at pages/innovation_application</p>

app/views/pages/innovation_details.html.erb
<p>find me at pages/innovation_details</p>

app/views/pages/make_event.html.erb
<p>find me at pages/make_event</p>
<%= Date.today %>

app/views/pages/products.html.erb
<p>find me at pages/products</p>

app/views/pages/volunteer.html.erb
<p>find me at pages/volunteer</p>